import socket
USER_ID_LENGTH = 128
HOST_IP = '127.0.0.1'
HOST_PORT = 12345
ENCODING = 'utf-8'
BUFFER = 2048
COMMAND_LEN_SIZE = 8
COMMAND_ID_LEN = 1
PATH_LEN_SIZE = 3
DEFAULT_USER_ID = '0' * USER_ID_LENGTH
DEFAULT_CLIENT_ID = 'x'

